resource_group_name   = "rg-lct-demo-poc-1"
location              = "Central India"
environment           = "dev"
storage_account_name  = "stalctdemopoc1"
app_service_plan_name = "asp-lct-demo"
app_service_name      = "helloapi"
blob_container_name   = "api-output"
logic_app_name        = "la-lct-demo-poc-1"