name: Deploy Hello API

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_PATH: api/HelloApi/HelloApi.csproj
  PUBLISH_DIR: publish

jobs:
  deploy-api:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} \
          --configuration Release \
          --output ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_SERVICE_NAME }}
          package: ${{ env.PUBLISH_DIR }}